rules:
  # ============================================
  # ОФИЦИАЛЬНЫЕ РУЛСЕТЫ
  # ============================================

  # Next.js Security - Dynamic Import
  - id: nextjs-dynamic-import
    patterns:
      - pattern: |
          import($FILE_PATH)
      - pattern-not-regex: |
          import\(['"`]/\.\./
      - pattern-not-inside: |
          safeDynamicImport($PATH)
    message: "Dynamic import without path validation. Use safeDynamicImport() from lib/dynamic-import-validator.ts for security."
    languages: [typescript, javascript]
    severity: WARNING
    paths:
      exclude:
        - lib/dynamic-import-validator.ts
    metadata:
      category: security
      technology: [nextjs]
      cwe: "CWE-20: Improper Input Validation"

  # OWASP A01:2021 - Broken Access Control
  - id: owasp-broken-access-control
    patterns:
      - pattern: |
          if ($USER.role !== $REQUIRED_ROLE) {
            throw new Error(...)
          }
      - pattern-not-inside: |
          if ($USER.role !== $REQUIRED_ROLE && $USER.role !== 'admin') {
            ...
          }
    message: "Broken access control: role check may be bypassed. Always check for ALL required roles including admin."
    languages: [typescript, javascript]
    severity: ERROR
    metadata:
      category: security
      owasp: "A01:2021 - Broken Access Control"
      cwe: "CWE-284: Improper Access Control"

  # React Security - dangerouslySetInnerHTML
  - id: react-dangerouslysetinnerhtml
    patterns:
      - pattern-regex: |
          dangerouslySetInnerHTML=\\{\\{\\s*__html:\\s*
    message: "Potential XSS via dangerouslySetInnerHTML. Ensure expression is properly sanitized."
    languages: [typescript, javascript]
    severity: WARNING
    metadata:
      category: security
      cwe: "CWE-79: Cross-site Scripting (XSS)"

  # ============================================
  # КАСТОМНЫЕ ПРАВИЛА: AI PROMPT INJECTION
  # ============================================

  - id: ai-prompt-injection-unsanitized-messages
    patterns:
      - pattern: |
          await streamText({
            model: $MODEL,
            messages: $MESSAGES,
            ...
          })
      - pattern-not: |
          await streamText({
            model: $MODEL,
            messages: sanitize($MESSAGES),
            ...
          })
    message: "AI prompt injection risk: messages passed to streamText without sanitization. Validate and sanitize user input before sending to AI model."
    languages: [typescript]
    severity: ERROR
    paths:
      include:
        - app/api/chat/**
        - app/api/**/route.ts
    metadata:
      category: security
      subcategory: [ai-security]
      cwe: "CWE-94: Improper Control of Generation of Code"
      confidence: HIGH
      likelihood: HIGH
      impact: HIGH
      references:
        - https://owasp.org/www-project-top-10-for-large-language-model-applications/

  - id: ai-prompt-injection-direct-user-input
    patterns:
      - pattern: |
          const { messages } = await req.json()
      - pattern-not-inside: |
          const schema = z.object({ messages: z.array(...) })
          const validated = schema.parse(...)
    message: "Direct use of user input in AI prompts without validation. Use Zod schema to validate message structure."
    languages: [typescript]
    severity: ERROR
    paths:
      include:
        - app/api/chat/**
    metadata:
      category: security
      subcategory: [ai-security, input-validation]
      cwe: "CWE-20: Improper Input Validation"

  - id: ai-file-upload-no-validation
    patterns:
      - pattern: |
          formData.get('file')
      - pattern-not-inside: |
          if ($FILE.size > ...) { ... }
      - pattern-not-inside: |
          if (!ALLOWED_TYPES.includes($FILE.type)) { ... }
    message: "File upload without size/type validation in AI components. Validate file.size and file.type before processing."
    languages: [typescript]
    severity: WARNING
    paths:
      include:
        - components/ai-elements/**
    metadata:
      category: security
      subcategory: [file-upload]
      cwe: "CWE-434: Unrestricted Upload of File with Dangerous Type"

  - id: ai-system-prompt-exposure
    patterns:
      - pattern: |
          const systemPrompt = "..."
      - pattern-inside: |
          export async function POST(...) { ... }
    message: "System prompt defined in API route may be exposed. Move to environment variables or secure config."
    languages: [typescript]
    severity: WARNING
    paths:
      include:
        - app/api/**
    metadata:
      category: security
      subcategory: [ai-security]

  # ============================================
  # AI COMPONENT RULES: components/ai-elements/**
  # ============================================

  - id: ai-component-user-input-to-messages
    patterns:
      - pattern: |
          setMessages($MESSAGES)
      - pattern-inside: |
          function $FUNC(...) {
            ...
          }
      - pattern-not-inside: |
          setMessages(z.array($SCHEMA).parse($MESSAGES))
    message: "User input passed to AI messages without validation in component. Use Zod schema to validate before setting messages."
    languages: [typescript]
    severity: ERROR
    paths:
      include:
        - components/ai-elements/**
    metadata:
      category: security
      subcategory: [ai-security, component-input]
      cwe: "CWE-20: Improper Input Validation"

  - id: ai-component-unchecked-props
    patterns:
      - pattern: |
          <$COMPONENT onSubmit={$HANDLER} />
      - pattern-inside: |
          function $HANDLER($EVENT) {
            ...
            const $PROMPT = $EVENT.target.$FIELD.value
            ...
          }
      - pattern-not-inside: |
          const $PROMPT = z.string().min(1).parse($EVENT.target.$FIELD.value)
    message: "User input from form fields used in AI prompt without validation. Sanitize and validate input before AI processing."
    languages: [typescript, javascript]
    severity: ERROR
    paths:
      include:
        - components/ai-elements/**
    metadata:
      category: security
      subcategory: [ai-security, form-input]
      cwe: "CWE-20: Improper Input Validation"

  - id: ai-component-file-content-unsanitized
    patterns:
      - pattern: |
          const content = $FILE.content
          ...
          addMessage(...)
      - pattern-not-inside: |
          const content = sanitize($FILE.content)
    message: "File content used in AI messages without sanitization. Sanitize file content to prevent prompt injection."
    languages: [typescript]
    severity: WARNING
    paths:
      include:
        - components/ai-elements/**
    metadata:
      category: security
      subcategory: [ai-security, file-upload]
      cwe: "CWE-94: Improper Control of Generation of Code"

  # ============================================
  # КАСТОМНЫЕ ПРАВИЛА: AUTH VULNERABILITIES
  # ============================================

  - id: auth-weak-fake-authentication
    patterns:
      - pattern: |
          if (email && password) {
            cookieStore.set({ name: 'auth_session', value: 'authenticated', ... })
            return { success: true, ... }
          }
    message: "DEMO CODE: Fake authentication detected. This is example code - replace with real auth before production (bcrypt, JWT, OAuth)."
    languages: [typescript]
    severity: WARNING
    paths:
      include:
        - app/@left/(_AUTH)/**
        - app/**/actions/auth.ts
    metadata:
      category: security
      subcategory: [authentication]
      cwe: "CWE-287: Improper Authentication"
      confidence: HIGH
      likelihood: HIGH
      impact: CRITICAL
      note: "Demo/example code - not for production use"

  - id: auth-no-rate-limiting
    patterns:
      - pattern: |
          export async function loginAction(...) {
            ...
          }
      - pattern-not-inside: |
          const rateLimiter = ...
          await rateLimiter.check(...)
    message: "Login action without rate limiting. Implement rate limiting to prevent brute-force attacks (e.g., upstash/ratelimit)."
    languages: [typescript]
    severity: ERROR
    paths:
      include:
        - app/**/actions/auth.ts
    metadata:
      category: security
      subcategory: [authentication, rate-limiting]
      cwe: "CWE-307: Improper Restriction of Excessive Authentication Attempts"

  - id: auth-session-fixation
    patterns:
      - pattern: |
          cookieStore.set({
            name: 'auth_session',
            value: $VALUE,
            ...
          })
      - pattern-not: |
          cookieStore.set({
            name: 'auth_session',
            value: crypto.randomUUID(),
            ...
          })
    message: "Session fixation risk: static session value. Use crypto.randomUUID() or secure token generation."
    languages: [typescript]
    severity: WARNING
    paths:
      include:
        - app/**/actions/auth.ts
    metadata:
      category: security
      subcategory: [session-management]
      cwe: "CWE-384: Session Fixation"

  - id: auth-no-password-hashing
    patterns:
      - pattern: |
          const password = formData.get('password')
      - pattern-not-inside: |
          await bcrypt.compare($PASSWORD, ...)
      - pattern-not-inside: |
          await argon2.verify(...)
    message: "Password used without hashing. Use bcrypt or argon2 for password verification."
    languages: [typescript]
    severity: ERROR
    paths:
      include:
        - app/**/actions/auth.ts
    metadata:
      category: security
      subcategory: [cryptography]
      cwe: "CWE-256: Plaintext Storage of a Password"

  - id: auth-jwt-no-verification
    patterns:
      - pattern: |
          import { ... } from 'jose'
      - pattern: |
          const token = cookies().get('...')
      - pattern-not-inside: |
          await jwtVerify($TOKEN, ...)
    message: "JWT token used without verification. Always verify JWT signatures with jwtVerify()."
    languages: [typescript]
    severity: ERROR
    paths:
      include:
        - app/**
        - lib/**
    metadata:
      category: security
      subcategory: [jwt]
      cwe: "CWE-347: Improper Verification of Cryptographic Signature"

  # ============================================
  # КАСТОМНЫЕ ПРАВИЛА: XSS & INJECTION
  # ============================================

  - id: api-xss-error-disclosure
    patterns:
      - pattern: |
          return new Response(
            JSON.stringify({
              error: ...,
              message: error instanceof Error ? error.message : ...,
            }),
            ...
          )
    message: "Error message disclosure in API response. Sanitize error.message to prevent information leakage."
    languages: [typescript]
    severity: WARNING
    paths:
      include:
        - app/api/**
    metadata:
      category: security
      subcategory: [information-disclosure]
      cwe: "CWE-209: Generation of Error Message Containing Sensitive Information"

  - id: api-sql-injection-risk
    patterns:
      - pattern: |
          db.query(`SELECT * FROM ... WHERE ... = ${$USER_INPUT}`)
      - pattern: |
          db.execute(`... ${$USER_INPUT} ...`)
    message: "SQL injection risk: user input in raw query. Use parameterized queries or ORM."
    languages: [typescript]
    severity: ERROR
    paths:
      include:
        - app/api/**
        - lib/**
    metadata:
      category: security
      subcategory: [injection]
      cwe: "CWE-89: SQL Injection"

  - id: api-nosql-injection
    patterns:
      - pattern: |
          db.collection(...).find({ $FIELD: $USER_INPUT })
      - pattern-not-inside: |
          const validated = schema.parse($USER_INPUT)
    message: "NoSQL injection risk: unvalidated user input in query. Validate with Zod schema."
    languages: [typescript]
    severity: ERROR
    paths:
      include:
        - app/api/**
    metadata:
      category: security
      subcategory: [injection]
      cwe: "CWE-943: Improper Neutralization of Special Elements in Data Query Logic"

  - id: api-cors-wildcard
    patterns:
      - pattern: |
          'Access-Control-Allow-Origin': '*'
    message: "CORS wildcard allows any origin. Restrict to specific domains in production."
    languages: [typescript]
    severity: WARNING
    paths:
      include:
        - app/api/**
    metadata:
      category: security
      subcategory: [cors]
      cwe: "CWE-942: Permissive Cross-domain Policy with Untrusted Domains"

  - id: xss-unsafe-html-rendering
    pattern: dangerouslySetInnerHTML
    message: "XSS risk: dangerouslySetInnerHTML detected. Use DOMPurify.sanitize() or SafeJsonLd component for JSON-LD structured data."
    languages: [typescript, javascript]
    severity: WARNING
    paths:
      include:
        - components/**
        - app/**
      exclude:
        - components/safe-json-ld.tsx
        - app/global-not-found.tsx
        - "**/__tests__/**"
        - "**/__mocks__/**"
    metadata:
      category: security
      subcategory: [xss]
      cwe: "CWE-79: Cross-site Scripting (XSS)"

  - id: xss-user-content-in-markdown
    pattern: ReactMarkdown
    message: "Review markdown rendering for XSS. Ensure dangerous HTML tags are disabled and links are sanitized."
    languages: [typescript, javascript]
    severity: INFO
    paths:
      include:
        - components/**
    metadata:
      category: security
      subcategory: [xss]

  # ============================================
  # ДОПОЛНИТЕЛЬНЫЕ ПРАВИЛА
  # ============================================

  - id: env-variable-exposure
    patterns:
      - pattern: |
          console.log(process.env.$VAR)
      - pattern: |
          console.error(process.env.$VAR)
    message: "Environment variable logged to console. Remove before production."
    languages: [typescript, javascript]
    severity: WARNING
    metadata:
      category: security
      subcategory: [secrets]

  - id: hardcoded-secrets
    patterns:
      - pattern: |
          const apiKey = "..."
      - pattern: |
          const secret = "..."
      - pattern: |
          const password = "..."
    message: "Hardcoded secret detected. Use environment variables."
    languages: [typescript, javascript]
    severity: ERROR
    metadata:
      category: security
      subcategory: [secrets]
      cwe: "CWE-798: Use of Hard-coded Credentials"

  - id: unsafe-redirect
    patterns:
      - pattern: |
          redirect($USER_INPUT)
      - pattern-not-inside: |
          if ($USER_INPUT.startsWith('/')) { redirect($USER_INPUT) }
    message: "Open redirect vulnerability. Validate redirect URL is internal."
    languages: [typescript]
    severity: ERROR
    paths:
      include:
        - app/**
    metadata:
      category: security
      subcategory: [redirect]
      cwe: "CWE-601: URL Redirection to Untrusted Site"
